Another attempt at failure counting for g++-4.8

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -173,12 +173,10 @@ install:
     fi
 
 before_script:
-  - CXX=${COMPILER} CXXFLAGS=${CXXFLAGS} ./check_errors.sh
-  - |
-    FAILURES=$?
-    if [[ ${CXX_STANDARD} == "11" && ${ERRORS} != "4" ]]; then
-      echo "Expected four failures from C++11 build, got " ${FAILURES}
-      exit 1
+  - CXX=${COMPILER} CXXFLAGS=${CXXFLAGS} ./check_errors.sh || \
+    FAILURES="$?" && if [[ ${CXX_STANDARD} == "11" && ${FAILURES} != "4" ]]; then \
+      echo "Expected four failures from C++11 build, got " ${FAILURES} ; \
+      exit 1 ; \
     fi
   - mkdir build && cd build
   - CXX=${COMPILER} cmake -DCXX_STANDARD="${CXX_STANDARD}" -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=${SANITIZE} ..
