Replacing own testing scripts to cmake ctest kcov using only on Linux Clean-up ci

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,18 +19,14 @@ matrix:
             - libelf-dev
             - libdw-dev
       env:
-        - COMPILER="clang++-3.7"
-      before_script:
+        - COMPILER="clang++-3.7" SANITIZE=true
+      before_install:
         # The clang runtime for the address sanitizer is missing from the
         # apt, hence the downloaded tarballs.
 
         - wget http://releases.llvm.org/3.7.1/clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
         - tar -xvf clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
         - sudo cp -n clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04/lib/clang/3.7.1/lib/linux/*.a /usr/lib/llvm-3.7/lib/clang/3.7.1/lib/linux/
-        - CXX=${COMPILER} ./check_errors.sh
-        - mkdir build && cd build
-        - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=true ..
-        - make -j 4 VERBOSE=1 self_test kcov
 
     - os: linux
       addons:
@@ -60,8 +56,8 @@ matrix:
             - libelf-dev
             - libdw-dev
       env:
-        - COMPILER="clang++-3.9"
-      before_script:
+        - COMPILER="clang++-3.9" SANITIZE=true
+      before_install:
         # Unlike with clang++-3.7, the runtime libraries exists with 3.9,
         # but still doesn't work because of gold linker version incompatibility.
         # The tarball download takes care of that.
@@ -69,10 +65,6 @@ matrix:
         - wget http://releases.llvm.org/3.9.1/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
         - tar -xvf clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
         - sudo cp clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04/lib/clang/3.9.1/lib/linux/*.a /usr/lib/llvm-3.9/lib/clang/3.9.1/lib/linux/
-        - CXX=${COMPILER} ./check_errors.sh
-        - mkdir build && cd build
-        - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=true ..
-        - make -j 4 VERBOSE=1 self_test kcov
 
     - os: linux
       addons:
@@ -224,18 +216,18 @@ install:
 before_script:
   - CXX=${COMPILER} CXXFLAGS=${CXXFLAGS} ./check_errors.sh ||
     FAILURES="$?" && if [[ ${CXX_STANDARD} == "11" && ${FAILURES} != "4" ]]; then
-      echo "Expected four failures from C++11 build, got " ${FAILURES} ;
-      exit 1 ;
+      echo "Expected four failures from C++11 build, got " ${FAILURES};
+      exit 1;
     fi
   - mkdir build && cd build
   - CXX=${COMPILER} cmake -DCXX_STANDARD="${CXX_STANDARD}" -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_JOB_ID='${TRAVIS_JOB_ID}' -DSANITIZE=${SANITIZE} ..
-  - make VERBOSE=1 self_test
+  - cmake --build . --target self_test --config Debug
 
 script:
-  make run_self_test
+  - ctest -V --output-on-failure -C Debug
 
 after_success:
   - |
     if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-      make VERBOSE=1 run_coverage
+      cmake --build . --target run_coverage --config Debug
     fi
